-- ============================================================================
-- trenmap · esquema Postgres + PostGIS
-- Migrado desde SQLite (contacts_backup) + capa geoespacial de tendencias
-- El orden de columnas replica EXACTAMENTE al SQLite de origen porque los
-- INSERT del volcado (02_data.sql) no llevan lista de columnas.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ----------------------------------------------------------------------------
-- Catálogos / tablas padre
-- ----------------------------------------------------------------------------
CREATE TABLE marital_status (
    status_id      TEXT PRIMARY KEY,
    marital_status TEXT NOT NULL
);

CREATE TABLE relationship_type (
    type_id TEXT PRIMARY KEY,
    label   TEXT NOT NULL
);

CREATE TABLE organization (
    organization_id TEXT PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE
);

-- ----------------------------------------------------------------------------
-- Núcleo: contactos (la tabla real con 571 filas; la antigua `contacts` vacía
-- del SQLite se descarta a propósito)
-- ----------------------------------------------------------------------------
CREATE TABLE contact (
    contact_id  TEXT PRIMARY KEY,
    first_name  TEXT NOT NULL,
    middle_name TEXT,
    surname     TEXT NOT NULL,
    birthdate   TEXT,                                  -- texto: formato mixto DD/MM/YYYY en origen
    gender      TEXT CHECK (gender IN ('MALE', 'FEMALE')),
    status_id   TEXT REFERENCES marital_status (status_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- Notas sueltas (independiente de contactos)
-- ----------------------------------------------------------------------------
CREATE TABLE notes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT,
    content      TEXT,
    modifiedDate TEXT
);

-- ----------------------------------------------------------------------------
-- Tablas hijas (FK -> contact)
-- ----------------------------------------------------------------------------
CREATE TABLE contact_relationship (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id         TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    related_contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    type_id            TEXT NOT NULL REFERENCES relationship_type (type_id),
    UNIQUE (contact_id, related_contact_id, type_id)
);

CREATE TABLE contact_organization (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id      TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    organization_id TEXT NOT NULL REFERENCES organization (organization_id),
    achievement     TEXT NOT NULL,
    date            TEXT
);

CREATE TABLE national_identity_card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id  TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    doc_type    TEXT NOT NULL,
    card_number TEXT NOT NULL,
    issue_date  TEXT,
    expiry_date TEXT
);

CREATE TABLE contact_phone (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    phone      TEXT NOT NULL,
    label      TEXT
);

CREATE TABLE contact_email (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    email      TEXT NOT NULL,
    label      TEXT
);

CREATE TABLE contact_note (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    note       TEXT NOT NULL
);

CREATE TABLE contact_url (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    url        TEXT NOT NULL,
    label      TEXT
);

CREATE TABLE contact_bank_account (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id     TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    bank_name      TEXT,
    account_number TEXT NOT NULL,
    account_type   TEXT,
    label          TEXT
);

CREATE TABLE contact_keyword (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    keyword    TEXT NOT NULL,
    UNIQUE (contact_id, keyword)
);

-- ============================================================================
-- CAPA trenmap · ubicación + preferencias/tendencias
-- ============================================================================

-- Ubicaciones de un contacto (casa, trabajo, finca...). Un contacto puede tener
-- varias. geom = punto exacto; geom_blurred = punto difuminado para mapas
-- públicos sin exponer el domicilio.
CREATE TABLE contact_location (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id   TEXT NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    kind         TEXT,                                 -- 'casa','trabajo','finca','principal'
    address      TEXT,
    geom         geography(Point, 4326) NOT NULL,
    geom_blurred geography(Point, 4326),
    is_primary   BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_contact_location_geom    ON contact_location USING GIST (geom);
CREATE INDEX idx_contact_location_blurred ON contact_location USING GIST (geom_blurred);
CREATE INDEX idx_contact_location_contact ON contact_location (contact_id);

-- Catálogo de preferencias/tendencias. kind agrupa el dominio.
CREATE TABLE trait (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind  TEXT NOT NULL,                               -- 'gastronomia','agricultura','politica','comercio'...
    label TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#38bdf8',             -- color hex para el mapa/leyenda
    UNIQUE (kind, label)
);

-- Relación contacto <-> preferencia, con intensidad y procedencia del dato.
CREATE TABLE contact_trait (
    contact_id TEXT   NOT NULL REFERENCES contact (contact_id) ON DELETE CASCADE,
    trait_id   BIGINT NOT NULL REFERENCES trait (id) ON DELETE CASCADE,
    weight     REAL   NOT NULL DEFAULT 1,              -- intensidad / confianza
    source     TEXT,                                   -- 'declarado','encuesta','inferido'
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (contact_id, trait_id)
);
CREATE INDEX idx_contact_trait_trait ON contact_trait (trait_id);

-- Semillas de ejemplo del catálogo de tendencias (con color)
INSERT INTO trait (kind, label, color) VALUES
    ('gastronomia',  'helados',              '#f472b6'),
    ('gastronomia',  'hornados',             '#f59e0b'),
    ('agricultura',  'pitahaya',             '#d946ef'),
    ('comercio',     'artesania',            '#a78bfa'),
    ('politica',     'tendencia: izquierda', '#ef4444'),
    ('politica',     'tendencia: centro',    '#eab308'),
    ('politica',     'tendencia: derecha',   '#3b82f6')
ON CONFLICT DO NOTHING;
