-- Zonas / sectores geográficos definidos por el administrador
CREATE TABLE IF NOT EXISTS zone (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    color      TEXT NOT NULL DEFAULT '#38bdf8',
    geom       geography(Polygon, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_zone_geom ON zone USING GIST (geom);
